server:
  port: 8082 # 为了测试负载均衡,换一个端口提供8082端口
spring:
  application:
    name: userserver # 注册到eruka的名称, restTemplate通过这个名字来调用,不区分大小写
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


#eureka:
# client:
#   register-with-eureka: true
#   fetchRegistry: true
#   service-url:  # eureka的注册地址信息
#     defaultZone: http://127.0.0.1:10086/eureka

# instance:
#   # 服务名称，客户端通过此名称来调用服务
#   appname: user-server
nacos:
  discovery:
    server-addr: 127.0.0.1:8848