server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.31.200
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.200:3306/changgou_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: robod666
  cookieDomain: localhost
  cookieMaxAge: -1

encrypt:
  key-store:
    location: classpath:/robod666.jks # 证书路径
    secret: robod666                  # 密钥
    alias: robod666                   # 证书的别名
    password: robod666                # 证书密码

logging:
  level:
    com: debug