server:
  port: 18090
spring:
  application:
    name: wechatpay
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.31.200
    port: 5672
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE

#微信支付信息配置
wechat:
  # 应用id
  appid: wx8397f8696b538317
  # 商户号id
  mch_id: 1473426802
  # 密钥
  key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  # 支付回调地址
  notify_url: http://robod123.cn1.utools.club/wechat/pay/notify/url