server:
  port: 18091
spring:
  application:
    name: seckill
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.200:3306/changgou_seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  rabbitmq:
    host: 192.168.31.200 #mq的服务器地址
    username: root #账号
    password: 123456 #密码
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.31.200
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE

logging:
  level:
    com: debug  # 不加这个MyBatis Log插件不打印sql语句

mybatis:
  configuration:
    map-underscore-to-camel-case: true

mq:
  pay:
    exchange:
      order: exchange.seckill_order
    queue:
      seckillorder: queue.seckillorder
    routing:
      key: routing.seckill_order
