server:
  port: 18086

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
  application:
    name: search-web
  main:
    allow-bean-definition-overriding: true
spring:
  thymeleaf:
    #构建URL时预先查看名称的前缀，默认就是这个，写在这里是怕忘了怎么配置
    prefix: classpath:/templates/
    suffix: .html   #后缀
    cache: false    #禁止缓存

ribbon:
  ReadTimeout: 500000   # Feign请求读取数据超时时间

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000   # feign连接超时时间

#logging:
#  level:
#    com: debug